//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.Activity1 = new HashSet<Activity>();
            this.OrgActivity = new HashSet<OrgActivity>();
            this.People = new HashSet<People>();
        }
    
        public int IdActivity { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdSubActivity { get; set; }
        public string Adress { get; set; }
        public int Num { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Activity> Activity1 { get; set; }
        public virtual Activity Activity2 { get; set; }
        public virtual ICollection<OrgActivity> OrgActivity { get; set; }
        public virtual ICollection<People> People { get; set; }
    }
}
