//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organisator
    {
        public Organisator()
        {
            this.OrgActivity = new HashSet<OrgActivity>();
        }
    
        public int IdOrganisateur { get; set; }
        public string Nom { get; set; }
        public string NickName { get; set; }
        public string Mail { get; set; }
        public string Tel { get; set; }
    
        public virtual ICollection<OrgActivity> OrgActivity { get; set; }
    }
}
