//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public People()
        {
            this.Activity = new HashSet<Activity>();
        }
    
        public int IdParticipant { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<Activity> Activity { get; set; }
    }
}
